### ISSUE TITLE
Feedback: WAL Failover

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#19696]
Page: https://cockroachlabs.com/docs/v24.3/wal-failover.html

## What is the reason for your feedback?

[ ] Missing the information I need

[ ] Too complicated

[ ] Out of date

[x] Something is broken

[ ] Other

## Additional details
Could we add `auditable:false` in logging section? Because 
> File-based audit logging cannot coexist with the buffering configuration, so disable either buffering or auditable.
According to (https://www.cockroachlabs.com/docs/v25.2/logging-best-practices.html#auditable) 
If a user doesn't add it to below, 
```
file-defaults:
 buffered-writes: false
 buffering:
   max-staleness: 1s
   flush-trigger-size: 256KiB
   max-buffer-size: 50MiB
```
it results in an error.
` +file group "sql-auth": File-based audit logging cannot coexist with buffering configuration. Disable either the buffering configuration ("buffering") or auditable log ("auditable") configuration.` 

Jira issue: DOC-13861
