### ISSUE TITLE
New Doc Proposal 

### ISSUE THREAD

**Issue by radioactivekraken** [cockroachdb/docs#2317]
## Title
Orchestrate CockroachDB with OpenShift

## Description
Orchestrate CockroachDB with OpenShift Origins and Red Hat OpenShift Platform. 

## Outline
The required modification from Kubernetes (kubectl) to OpenShift Client (oc) commands isn't a lot of work. Not everything ctrl+c -> ctrl+v. I ran into issues with the PV provision during the OpenShift deployment. I will include my changes below in the code section. 

## Expected Audience
Red Hat has a massive audience of customers that are willing to pay for Open Source software. OpenShift doesn't have a cohesive story running scalible databases. They have in tech preview db with replica, but they are not ready for prime time. I think Red Hat and our customers could be a rich audience. 

## Code section
```
volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
```
