### ISSUE TITLE
Create Kubernetes version of low-latency multi-region tutorial with Secure Mode

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/docs#5348]
Andrew Deally (drewdeally) commented:

We need to show how to run a multi-region app in a multi-region Kubernetes deployment. The best route is to expand our multi-region tutorial featuring MovR and geo-partitioning and duplicate indexes to a Kubernetes-based deployment. We'd end up with two options for the same tutorial: Manual vs. Kubernetes.

Original notes below.

----

Issue: create customer facing a doc for running Movr with K8/Secure multi-region cluster
also can be re-used for Sales Demo

Using https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html

Results multi-regional Cluster us-east1-b, us-west1-b and us-central1-central

kubectl config get-contexts
```
CURRENT   NAME                                                    CLUSTER                                                 AUTHINFO                                                NAMESPACE
          gke_cockroach-rslee_us-central1-b_cockroachdb-central   gke_cockroach-rslee_us-central1-b_cockroachdb-central   gke_cockroach-rslee_us-central1-b_cockroachdb-central   
          gke_cockroach-rslee_us-east1-b_cockroachdb-east         gke_cockroach-rslee_us-east1-b_cockroachdb-east         gke_cockroach-rslee_us-east1-b_cockroachdb-east         
          gke_cockroach-rslee_us-east1-c_cockroachdb              gke_cockroach-rslee_us-east1-c_cockroachdb              gke_cockroach-rslee_us-east1-c_cockroachdb              
*         gke_cockroach-rslee_us-west1-b_client-west              gke_cockroach-rslee_us-west1-b_client-west              gke_cockroach-rslee_us-west1-b_client-west              
          gke_cockroach-rslee_us-west1-b_cockroachdb-west         gke_cockroach-rslee_us-west1-b_cockroachdb-west         gke_cockroach-rslee_us-west1-b_cockroachdb-west         
          minikube                                                minikube                                                minikube                                                
```

![image](https://user-images.githubusercontent.com/39496073/64081440-f0fdb980-ccce-11e9-98bc-9adead36ee49.png)

This might be an issue had to correct zone configs from Jesse Demo steps
![image](https://user-images.githubusercontent.com/39496073/64081446-f9ee8b00-ccce-11e9-953d-5547135e08da.png]

using conceptual steps from https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/109314241/Multi-Region+Geo-Partitioned+Replicas

created a yaml for movR image with access to certs for secure access

```
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-movr
  labels:
    app: cockroachdb-client
spec:
  serviceAccountName: cockroachdb
  containers:
  - name: cockroachdb-client
#    image: cockroachdb/movr
    image: cockroachdb/movr:19.03.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
    # Keep a pod open indefinitely so kubectl exec can be used to get a shell to it
    # and run cockroach client commands, such as cockroach sql, cockroach node status, etc.
    command:
    - sleep
    - "2147483648" # 2^31
  # This pod isn't doing anything important, so don't bother waiting to terminate it.
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    secret:
      secretName: cockroachdb.client.root
      defaultMode: 256
```

create one movR client in central, east and west

```
kubectl create -f movr.yaml --context=gke_cockroach-rslee_us-central1-b_cockroachdb-central
 kubectl create -f movr.yaml --context=gke_cockroach-rslee_us-east1-b_cockroachdb-east
 kubectl create -f movr.yaml --context=gke_cockroach-rslee_us-west1-b_cockroachdb-west
```

Load data in West POD
```
kubectl exec -it cockroachdb-movr  --context=gke_cockroach-rslee_us-west1-b_cockroachdb-west --python loadmovr.py --url "postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key" load --num-users 100 --num-rides 100 --num-vehicles 10 
[INFO] (MainThread) connected to movr database @ postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key
```

Run Workload in West
```
kubectl exec -it cockroachdb-movr  --context=gke_cockroach-rslee_us-west1-b_cockroachdb-west -- python loadmovr.py --url "postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key" --num-threads=15 run --city="seattle"
[INFO] (MainThread) connected to movr database @ postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key
[INFO] (MainThread) simulating movr load for cities ['seattle']
[INFO] (MainThread) warming up....
[INFO] (MainThread) starting load
```
Run Workload in Central
```
kubectl exec -it cockroachdb-movr  --context=gke_cockroach-rslee_us-central1-b_cockroachdb-central -- python loadmovr.py --url "postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key" --num-threads=15 run --city="chicago"
[INFO] (MainThread) connected to movr database @ postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key
[INFO] (MainThread) simulating movr load for cities ['chicago']
[INFO] (MainThread) warming up....
[INFO] (MainThread) starting load
```
Run Workload in East
```
kubectl exec -it cockroachdb-movr  --context=gke_cockroach-rslee_us-east1-b_cockroachdb-east -- python loadmovr.py --url "postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key" --num-threads=15 run --city="new york"
[INFO] (MainThread) connected to movr database @ postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key
\[INFO] (MainThread) connected to movr database @ postgres://root@cockroachdb-public:26257/movr?sslmode=verify-full&sslrootcert=/cockroach-certs/ca.crt&sslcert=/cockroach-certs/client.root.crt&sslkey=/cockroach-certs/client.root.key
[INFO] (MainThread) simulating movr load for cities ['new york']
[INFO] (MainThread) warming up....
[INFO] (MainThread) starting load
```

movr reconfiguration with Zones to reduce Latency using geo-partitioning feature to be applied license

```
ALTER TABLE users PARTITION BY LIST (city) ( PARTITION new_york VALUES IN ('new york'), PARTITION chicago VALUES IN ('chicago'), PARTITION seattle VALUES IN ('seattle') );
ALTER TABLE vehicles PARTITION BY LIST (city) ( PARTITION new_york VALUES IN ('new york'), PARTITION chicago VALUES IN ('chicago'), PARTITION seattle VALUES IN ('seattle') );
ALTER INDEX vehicles_auto_index_fk_city_ref_users PARTITION BY LIST (city) ( PARTITION new_york_idx VALUES IN ('new york'), PARTITION chicago_idx VALUES IN ('chicago'), PARTITION seattle_idx VALUES IN ('seattle') );
ALTER TABLE rides PARTITION BY LIST (city) ( PARTITION new_york VALUES IN ('new york'), PARTITION chicago VALUES IN ('chicago'), PARTITION seattle VALUES IN ('seattle') );
ALTER INDEX rides_auto_index_fk_city_ref_users PARTITION BY LIST (city) ( PARTITION new_york_idx1 VALUES IN ('new york'), PARTITION chicago_idx1 VALUES IN ('chicago'), PARTITION seattle_idx1 VALUES IN ('seattle') );
ALTER INDEX rides_auto_index_fk_vehicle_city_ref_vehicles PARTITION BY LIST (vehicle_city) ( PARTITION new_york_idx2 VALUES IN ('new york'), PARTITION chicago_idx2 VALUES IN ('chicago'), PARTITION seattle_idx2 VALUES IN ('seattle') );


ALTER PARTITION new_york OF TABLE movr.users CONFIGURE ZONE USING constraints='[+zone=us-east1-b]'; ALTER PARTITION chicago OF TABLE movr.users CONFIGURE ZONE USING constraints='[+zone=us-central1-b]'; ALTER PARTITION seattle OF TABLE movr.users CONFIGURE ZONE USING constraints='[+zone=us-west1-b]';
ALTER PARTITION new_york OF TABLE movr.vehicles CONFIGURE ZONE USING constraints='[+zone=us-east1-b]'; ALTER PARTITION chicago OF TABLE movr.vehicles CONFIGURE ZONE USING constraints='[+zone=us-central1-b]'; ALTER PARTITION seattle OF TABLE movr.vehicles CONFIGURE ZONE USING constraints='[+zone=us-west1-b]';
ALTER PARTITION new_york_idx OF TABLE movr.vehicles CONFIGURE ZONE USING constraints='[+zone=us-east1-b]'; ALTER PARTITION chicago_idx OF TABLE movr.vehicles CONFIGURE ZONE USING constraints='[+zone=us-central1-b]'; ALTER PARTITION seattle_idx OF TABLE movr.vehicles CONFIGURE ZONE USING constraints='[+zone=us-west1-b]';
ALTER PARTITION new_york OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-east1-b]'; ALTER PARTITION chicago OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-central1-b]'; ALTER PARTITION seattle OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-west1-b]';
ALTER PARTITION new_york_idx1 OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-east1-b]'; ALTER PARTITION chicago_idx1 OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-central1-b]'; ALTER PARTITION seattle_idx1 OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-west1-b]';
ALTER PARTITION new_york_idx2 OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-east1-b]'; ALTER PARTITION chicago_idx2 OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-central1-b]'; ALTER PARTITION seattle_idx2 OF TABLE movr.rides CONFIGURE ZONE USING constraints='[+zone=us-west1-b)';
```

Using Secure Client modify the schema

```
kubectl exec -it cockroachdb-client-secure-central --context=gke_cockroach-rslee_us-central1-b_cockroachdb-central -- ./cockroach sql --certs-dir=/cockroach-certs --host=cockroachdb-public -d movr < movr.sql
Unable to use a TTY - input is not a terminal or the right kind of file
ALTER TABLE
ALTER TABLE
ALTER INDEX
ALTER TABLE
ALTER INDEX
ALTER INDEX
CONFIGURE ZONE 1
CONFIGURE ZONE 1
CONFIGURE ZONE 1
CONFIGURE ZONE 1
CONFIGURE ZONE 1
CONFIGURE ZONE 1 
```

Secure clients per region

```
cat client-secure-central.yaml
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure-central
  labels:
    app: cockroachdb-client
spec:
  serviceAccountName: cockroachdb
  containers:
  - name: cockroachdb-client
    image: cockroachdb/cockroach:v19.1.3
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
    # Keep a pod open indefinitely so kubectl exec can be used to get a shell to it
    # and run cockroach client commands, such as cockroach sql, cockroach node status, etc.
    command:
    - sleep
    - "2147483648" # 2^31
  # This pod isn't doing anything important, so don't bother waiting to terminate it.
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    secret:
      secretName: cockroachdb.client.root
      defaultMode: 256

cat client-secure-east.yaml
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure-east
  labels:
    app: cockroachdb-client
spec:
  serviceAccountName: cockroachdb
  containers:
  - name: cockroachdb-client
    image: cockroachdb/cockroach:v19.1.3
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
    # Keep a pod open indefinitely so kubectl exec can be used to get a shell to it
    # and run cockroach client commands, such as cockroach sql, cockroach node status, etc.
    command:
    - sleep
    - "2147483648" # 2^31
  # This pod isn't doing anything important, so don't bother waiting to terminate it.
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    secret:
      secretName: cockroachdb.client.root
      defaultMode: 256


 cat client-secure-west.yaml
apiVersion: v1
kind: Pod
metadata:
  name: cockroachdb-client-secure-west
  labels:
    app: cockroachdb-client
spec:
  serviceAccountName: cockroachdb
  containers:
  - name: cockroachdb-client
    image: cockroachdb/cockroach:v19.1.3
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: client-certs
      mountPath: /cockroach-certs
    # Keep a pod open indefinitely so kubectl exec can be used to get a shell to it
    # and run cockroach client commands, such as cockroach sql, cockroach node status, etc.
    command:
    - sleep
    - "2147483648" # 2^31
  # This pod isn't doing anything important, so don't bother waiting to terminate it.
  terminationGracePeriodSeconds: 0
  volumes:
  - name: client-certs
    secret:
      secretName: cockroachdb.client.root
      defaultMode: 256

```

![image](https://user-images.githubusercontent.com/39496073/64081534-9a917a80-ccd0-11e9-8544-e51625015d1d.png)

![image](https://user-images.githubusercontent.com/39496073/64081541-a11ff200-ccd0-11e9-89e5-4504dd18bc15.png)

![image](https://user-images.githubusercontent.com/39496073/64081544-ada44a80-ccd0-11e9-9eb9-69defc456f0c.png)

YCSB and TPCC is next:
