### ISSUE TITLE
Kubernetes performance YAML file contains broken link

### ISSUE THREAD

**Issue by ricardocrdb** [cockroachdb/docs#5602]
The link mentioned in the performance YAML file to address the Storage Class configuration is broken, I am getting a 404 error when attempting to access it. The page that has the file is https://github.com/cockroachdb/docs/blob/master/v19.2/kubernetes-performance.md, and the file itself is https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/performance/cockroachdb-statefulset-secure.yaml.
```
      # TODO: This specifically asks for a storage class with the name "ssd". A
      # storage class of this name doesn't exist by default. See our docs for
      # more information on how to create an optimized storage class for use here:
      # https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes-performance.html#disk-type
      storageClassName: ssd
      resources:
        requests:
          # TODO: This asks for a fairly large disk by default because on
          # certain popular clouds there is a direct correlation between disk
          # size and the IOPS provisioned to the disk. Change this as necessary
          # to suit your needs, but be aware that smaller disks will typically
          # mean worse performance.
          storage: 1024Gi
```
