### ISSUE TITLE
Document use of custom CA with Prometheus

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#6320]
Relates to #4696 

Our Prometheus operator config defaults to using the Kubernetes CA to sign the cert. When deploying with a custom CA, the `ca.crt` needs to be added to Kubernetes as a secret, mounted on the Prometheus pod, and then referenced in the Prometheus config.

**Comment by taroface** [comment]
Ran through this with @DuskEagle and was able to load the custom cert onto the Prometheus pod as a configMap. However, the CockroachDB nodes are incorrectly being reported as `DOWN` due to the certificate not being associated with the IP of each pod.

```
Get https://10.40.1.5:8080/_status/vars: x509: certificate is valid for 127.0.0.1, not 10.40.1.5
```

To resolve this, the Prometheus operator needs to send an HTTP request to e.g. `cockroachdb-0.cockroachdb:8080` instead of `<pod IP address>:8080` in order to find the cert valid. We need to investigate how this can be done.

CockroachCloud skips cert verification because of a similar issue with the UI certificate not having the pod's IP address in the name: https://github.com/cockroachlabs/managed-service/blob/489c48d9b3c31d2a8e8c41182f4e8d14583d462c/pkg/kube/kubecreate/monitoring/prometheus.go#L293

**Comment by taroface** [comment]
According to @cjireland:

> In the prometheus monitoring I am setting up across a secure cluster, the ServiceMonitor has to have:

```
  endpoints:
  - port: http
    path: /_status/vars
    tlsConfig:
      # The HTTPS certs are signed by the kubernetes internal
      # certificate authority.
         caFile:   "/etc/prometheus/secrets/cockroachdb.client.root/ca.crt"
      certFile: "/etc/prometheus/secrets/cockroachdb.client.root/client.root.crt"
      keyFile:  "/etc/prometheus/secrets/cockroachdb.client.root/client.root.key"
      # insecureSkipVerify: true
      # This overrides the hostname verification check for the admin
      # UI port to match our quickstart secure-mode cluster setup.
      serverName: "127.0.0.1"
```

> The Prometheus resource had to be modified to load the certificate as follows:

```
# Have prometheus-operator run a replicated Prometheus cluster
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: cockroachdb
  labels:
    app: cockroachdb
spec:
  serviceAccountName: prometheus
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager-cockroachdb
      port: web
  serviceMonitorSelector:
    matchLabels:
      prometheus: cockroachdb
  serviceMonitorNamespaceSelector:
    matchLabels:
      prometheus: cockroachdb
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: cockroachdb
  secrets: ["cockroachdb.client.root"]
```

Prometheus only needs ca.crt, not a client cert/key.
